version: '3.3'

services:
  traefik_proxy:
    image: traefik:alpine
    command:
      - --logLevel=DEBUG
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.email=YOUR_EMAIL_HERE
      - --acme.storage=/etc/traefik/acme.json
      - --acme.entryPoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.OnHostRule=true
      - --acme.onDemand=true
      - --acme.acmeLogging=true
      - --web
      - --docker
      - --docker.watch
      - --docker.exposedbydefault=false
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik:/etc/traefik
    labels:
      - traefik.docker.network=webgateway
      - traefik.frontend.rule=Host:YOUR_DOMAIN_HERE;PathPrefixStrip:/traefik
      - traefik.port=8080
      - traefik.enable=true

networks:
  webgateway:
    external: true
